In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns  
%matplotlib inline

In [72]:
df = pd.read_csv('googleplaystore.csv')

In [73]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [74]:
df.shape

(10841, 13)

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [76]:
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [77]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [78]:
df['Reviews'].unique()

<StringArray>
[   '159',    '967',  '87510', '215644',    '167',    '178',  '36815',
  '13791',    '121',  '13880',
 ...
   '2036',  '56496', '376223',    '785',   '5775',    '885',  '88486',
    '603',   '1195', '398307']
Length: 6002, dtype: str

In [79]:
df['Reviews'].astype(int)

ValueError: invalid literal for int() with base 10: '3.0M'

In [ ]:
df['Reviews'].str.isnumeric().sum()

np.int64(10840)

In [ ]:
df[~df['Reviews'].str.isnumeric()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [ ]:
df_copy = df.copy()

In [ ]:
df_copy = df_copy.drop(df_copy.index[10472])

In [ ]:
df_copy[~df_copy['Reviews'].str.isnumeric()]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [ ]:
df_copy['Reviews'] = df_copy['Reviews'].astype(int)

In [ ]:
df_copy.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            10840 non-null  str
 5   Installs        10840 non-null  str
 6   Type            10839 non-null  str
 7   Price           10840 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), int64(1), str(11)
memory usage: 1.2 MB

In [ ]:
df_copy['Size'].unique()

<StringArray>
[  '19M',   '14M',  '8.7M',   '25M',  '2.8M',  '5.6M',   '29M',   '33M',
  '3.1M',   '28M',
 ...
  '467k',  '157k',   '44k',  '676k',   '67k',  '552k',  '885k', '1020k',
  '582k',  '619k']
Length: 461, dtype: str

In [ ]:
print(list(df_copy['Size'].unique()))

['19000', '14000', '8.7000', '25000', '2.8000', '5.6000', '29000', '33000', '3.1000', '28000', '12000', '20000', '21000', '37000', '2.7000', '5.5000', '17000', '39000', '31000', '4.2000', '7.0000', '23000', '6.0000', '6.1000', '4.6000', '9.2000', '5.2000', '11000', '24000', 'Varies with device', '9.4000', '15000', '10000', '1.2000', '26000', '8.0000', '7.9000', '56000', '57000', '35000', '54000', '201', '3.6000', '5.7000', '8.6000', '2.4000', '27000', '2.5000', '16000', '3.4000', '8.9000', '3.9000', '2.9000', '38000', '32000', '5.4000', '18000', '1.1000', '2.2000', '4.5000', '9.8000', '52000', '9.0000', '6.7000', '30000', '2.6000', '7.1000', '3.7000', '22000', '7.4000', '6.4000', '3.2000', '8.2000', '9.9000', '4.9000', '9.5000', '5.0000', '5.9000', '13000', '73000', '6.8000', '3.5000', '4.0000', '2.3000', '7.2000', '2.1000', '42000', '7.3000', '9.1000', '55000', '23', '6.5000', '1.5000', '7.5000', '51000', '41000', '48000', '8.5000', '46000', '8.3000', '4.3000', '4.7000', '3.3000', '40000', '7.8000', '8.8000', '6.6000', '5.1000', '61000', '66000', '79', '8.4000', '118', '44000', '695', '1.6000', '6.2000', '18', '53000', '1.4000', '3.0000', '5.8000', '3.8000', '9.6000', '45000', '63000', '49000', '77000', '4.4000', '4.8000', '70000', '6.9000', '9.3000', '10.0000', '8.1000', '36000', '84000', '97000', '2.0000', '1.9000', '1.8000', '5.3000', '47000', '556', '526', '76000', '7.6000', '59000', '9.7000', '78000', '72000', '43000', '7.7000', '6.3000', '334', '34000', '93000', '65000', '79000', '100000', '58000', '50000', '68000', '64000', '67000', '60000', '94000', '232', '99000', '624', '95000', '8.5', '41', '292', '11', '80000', '1.7000', '74000', '62000', '69000', '75000', '98000', '85000', '82000', '96000', '87000', '71000', '86000', '91000', '81000', '92000', '83000', '88000', '704', '862', '899', '378', '266', '375', '1.3000', '975', '980', '4.1000', '89000', '696', '544', '525', '920', '779', '853', '720', '713', '772', '318', '58', '241', '196', '857', '51', '953', '865', '251', '930', '540', '313', '746', '203', '26', '314', '239', '371', '220', '730', '756', '91', '293', '17', '74', '14', '317', '78', '924', '902', '818', '81', '939', '169', '45', '475', '965', '90000', '545', '61', '283', '655', '714', '93', '872', '121', '322', '1.0000', '976', '172', '238', '549', '206', '954', '444', '717', '210', '609', '308', '705', '306', '904', '473', '175', '350', '383', '454', '421', '70', '812', '442', '842', '417', '412', '459', '478', '335', '782', '721', '430', '429', '192', '200', '460', '728', '496', '816', '414', '506', '887', '613', '243', '569', '778', '683', '592', '319', '186', '840', '647', '191', '373', '437', '598', '716', '585', '982', '222', '219', '55', '948', '323', '691', '511', '951', '963', '25', '554', '351', '27', '82', '208', '913', '514', '551', '29', '103', '898', '743', '116', '153', '209', '353', '499', '173', '597', '809', '122', '411', '400', '801', '787', '237', '50', '643', '986', '97', '516', '837', '780', '961', '269', '20', '498', '600', '749', '642', '881', '72', '656', '601', '221', '228', '108', '940', '176', '33', '663', '34', '942', '259', '164', '458', '245', '629', '28', '288', '775', '785', '636', '916', '994', '309', '485', '914', '903', '608', '500', '54', '562', '847', '957', '688', '811', '270', '48', '329', '523', '921', '874', '981', '784', '280', '24', '518', '754', '892', '154', '860', '364', '387', '626', '161', '879', '39', '970', '170', '141', '160', '144', '143', '190', '376', '193', '246', '73', '658', '992', '253', '420', '404', '470', '226', '240', '89', '234', '257', '861', '467', '157', '44', '676', '67', '552', '885', '1020', '582', '619']

In [ ]:
df_copy['Size'].isnull().sum()

np.int64(0)

In [ ]:
df_copy['Size'] = df_copy['Size'].str.replace('M', '000')
df_copy['Size'] = df_copy['Size'].str.replace('k', '')
df_copy['Size'] = df_copy['Size'].replace('Varies with device', np.nan)
df_copy['Size'] = df_copy['Size'].astype(float)

In [ ]:
df_copy.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            9145 non-null   float64
 5   Installs        10840 non-null  str
 6   Type            10839 non-null  str
 7   Price           10840 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(2), int64(1), str(10)
memory usage: 1.2 MB

In [ ]:
df_copy['Size']

0        19000.0
1        14000.0
2            8.7
3        25000.0
4            2.8
          ...
10836    53000.0
10837        3.6
10838        9.5
10839        NaN
10840    19000.0
Name: Size, Length: 10840, dtype: float64

In [ ]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [ ]:
df_copy['Installs'].unique()

<StringArray>
[     '10000',     '500000',    '5000000',   '50000000',     '100000',
      '50000',    '1000000',   '10000000',       '5000',  '100000000',
 '1000000000',       '1000',  '500000000',         '50',        '100',
        '500',         '10',          '1',          '5',          '0']
Length: 20, dtype: str

In [ ]:
df_copy['Price'].unique()

<StringArray>
[     '0',   '4.99',   '3.99',   '6.99',   '1.49',   '2.99',   '7.99',
   '5.99',   '3.49',   '1.99',   '9.99',   '7.49',   '0.99',   '9.00',
   '5.49',  '10.00',  '24.99',  '11.99',  '79.99',  '16.99',  '14.99',
   '1.00',  '29.99',  '12.99',   '2.49',  '10.99',   '1.50',  '19.99',
  '15.99',  '33.99',  '74.99',  '39.99',   '3.95',   '4.49',   '1.70',
   '8.99',   '2.00',   '3.88',  '25.99', '399.99',  '17.99', '400.00',
   '3.02',   '1.76',   '4.84',   '4.77',   '1.61',   '2.50',   '1.59',
   '6.49',   '1.29',   '5.00',  '13.99', '299.99', '379.99',  '37.99',
  '18.99', '389.99',  '19.90',   '8.49',   '1.75',  '14.00',   '4.85',
  '46.99', '109.99', '154.99',   '3.08',   '2.59',   '4.80',   '1.96',
  '19.40',   '3.90',   '4.59',  '15.46',   '3.04',   '4.29',   '2.60',
   '3.28',   '4.60',  '28.99',   '2.95',   '2.90',   '1.97', '200.00',
  '89.99',   '2.56',  '30.99',   '3.61', '394.99',   '1.26',   '1.20',
   '1.04']
Length: 92, dtype: str

In [ ]:
chars_to_remove = ['+', ',', '$']
cols_to_clean = ['Installs', 'Price']
for item in chars_to_remove:
    for cols in cols_to_clean:
        df_copy[cols] = df_copy[cols].str.replace(item, '')

In [ ]:
df_copy['Installs'].unique()

<StringArray>
[     '10000',     '500000',    '5000000',   '50000000',     '100000',
      '50000',    '1000000',   '10000000',       '5000',  '100000000',
 '1000000000',       '1000',  '500000000',         '50',        '100',
        '500',         '10',          '1',          '5',          '0']
Length: 20, dtype: str

In [ ]:
df_copy['Price'].unique()

<StringArray>
[     '0',   '4.99',   '3.99',   '6.99',   '1.49',   '2.99',   '7.99',
   '5.99',   '3.49',   '1.99',   '9.99',   '7.49',   '0.99',   '9.00',
   '5.49',  '10.00',  '24.99',  '11.99',  '79.99',  '16.99',  '14.99',
   '1.00',  '29.99',  '12.99',   '2.49',  '10.99',   '1.50',  '19.99',
  '15.99',  '33.99',  '74.99',  '39.99',   '3.95',   '4.49',   '1.70',
   '8.99',   '2.00',   '3.88',  '25.99', '399.99',  '17.99', '400.00',
   '3.02',   '1.76',   '4.84',   '4.77',   '1.61',   '2.50',   '1.59',
   '6.49',   '1.29',   '5.00',  '13.99', '299.99', '379.99',  '37.99',
  '18.99', '389.99',  '19.90',   '8.49',   '1.75',  '14.00',   '4.85',
  '46.99', '109.99', '154.99',   '3.08',   '2.59',   '4.80',   '1.96',
  '19.40',   '3.90',   '4.59',  '15.46',   '3.04',   '4.29',   '2.60',
   '3.28',   '4.60',  '28.99',   '2.95',   '2.90',   '1.97', '200.00',
  '89.99',   '2.56',  '30.99',   '3.61', '394.99',   '1.26',   '1.20',
   '1.04']
Length: 92, dtype: str

In [ ]:
df_copy['Installs'] = df_copy['Installs'].astype('int')
df_copy['Price'] = df_copy['Price'].astype('float')

In [ ]:
df_copy.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            9145 non-null   float64
 5   Installs        10840 non-null  int64
 6   Type            10839 non-null  str
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(3), int64(2), str(8)
memory usage: 1.2 MB

In [ ]:
df_copy['Last Updated'].unique()

<StringArray>
[   'January 7, 2018',   'January 15, 2018',     'August 1, 2018',
       'June 8, 2018',      'June 20, 2018',     'March 26, 2017',
     'April 26, 2018',      'June 14, 2018', 'September 20, 2017',
       'July 3, 2018',
 ...
  'November 23, 2015',      'June 17, 2012',  'February 27, 2015',
  'December 18, 2013',   'February 6, 2012',  'November 25, 2014',
       'May 19, 2016',   'January 20, 2014',  'February 16, 2014',
     'March 23, 2014']
Length: 1377, dtype: str

In [ ]:
df_copy['Last Updated'] = pd.to_datetime(df_copy['Last Updated'])

In [ ]:
df_copy['Day'] = df_copy['Last Updated'].dt.day
df_copy['Month'] = df_copy['Last Updated'].dt.month
df_copy['Year'] = df_copy['Last Updated'].dt.year

In [ ]:
df_copy.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            9145 non-null   float64
 5   Installs        10840 non-null  int64
 6   Type            10839 non-null  str
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  datetime64[us]
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
 13  Day             10840 non-null  int32
 14  Month           10840 non-null  int32
 15  Year            10840 non-null  int32
dtypes: datetime64[us](1), float64(3), int32(3), int64(2), str(7)
memory usage: 1.3 MB

In [ ]:
df_copy.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Day,Month,Year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,1,8,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,8,6,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,20,6,2018

In [ ]:
df_copy.to_csv('google_cleaned.csv')

In [ ]:
df_copy.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Day,Month,Year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,1,8,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,8,6,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,20,6,2018

In [ ]:
df_copy[df_copy.duplicated('App')].shape

(1181, 16)

In [ ]:
df_copy.shape

(10840, 16)

In [ ]:
df_copy = df_copy.drop_duplicates(subset=['App'],keep='first')

In [ ]:
df_copy.shape

(9659, 16)

In [ ]:
# numeric_features = [feature for feature in df_copy.columns if df_copy[feature].dtype != 'O'] 
# categorical_features = [feature for feature in df_copy.columns if df_copy[feature].dtype == 'O'] 

# print('We have {} numerical feactures: {}'.format(len(numeric_features), numeric_features))
# print('We have {} categorical feactures: {}'.format(len(categorical_features), categorical_features))

We have 16 numerical feactures: ['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver', 'Day', 'Month', 'Year']
We have 0 categorical feactures: []

In [82]:
df_copy.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Day,Month,Year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018

In [86]:
df_copy.info()

<class 'pandas.DataFrame'>
Index: 9659 entries, 0 to 10840
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9659 non-null   str
 1   Category        9659 non-null   str
 2   Rating          8196 non-null   float64
 3   Reviews         9659 non-null   int64
 4   Size            8432 non-null   float64
 5   Installs        9659 non-null   int64
 6   Type            9658 non-null   str
 7   Price           9659 non-null   float64
 8   Content Rating  9659 non-null   str
 9   Genres          9659 non-null   str
 10  Last Updated    9659 non-null   datetime64[us]
 11  Current Ver     9651 non-null   str
 12  Android Ver     9657 non-null   str
 13  Day             9659 non-null   int32
 14  Month           9659 non-null   int32
 15  Year            9659 non-null   int32
dtypes: datetime64[us](1), float64(3), int32(3), int64(2), str(7)
memory usage: 1.1 MB

In [91]:
import pandas as pd

# Standard, clean list comprehension using pandas data type properties
numeric_features = [feature for feature in df_copy.columns if df_copy[feature].dtype.kind in 'biufc']
categorical_features = [feature for feature in df_copy.columns if df_copy[feature].dtype.kind not in 'biufc']

# print columns
print('We have {} numerical features : {}'.format(len(numeric_features), numeric_features))
print('\nWe have {} categorical features : {}'.format(len(categorical_features), categorical_features))

We have 9 numerical features : ['Rating', 'Reviews', 'Size', 'Installs', 'Price', 'Last Updated', 'Day', 'Month', 'Year']

We have 7 categorical features : ['App', 'Category', 'Type', 'Content Rating', 'Genres', 'Current Ver', 'Android Ver']

In [93]:
for col in categorical_features:
    print(df_copy[col].value_counts(normalize=True)*100)
    print('-------------------------')

App
Photo Editor & Candy Camera & Grid & ScrapBook        0.010353
Coloring book moana                                   0.010353
U Launcher Lite – FREE Live Cool Themes, Hide Apps    0.010353
Sketch - Draw & Paint                                 0.010353
Pixel Draw - Number Art Coloring Book                 0.010353
                                                        ...
Sya9a Maroc - FR                                      0.010353
Fr. Mike Schmitz Audio Teachings                      0.010353
Parkinson Exercices FR                                0.010353
The SCP Foundation DB fr nn5n                         0.010353
iHoroscope - 2018 Daily Horoscope & Astrology         0.010353
Name: proportion, Length: 9659, dtype: float64
-------------------------
Category
FAMILY                 18.966767
GAME                    9.928564
TOOLS                   8.561963
BUSINESS                4.348276
MEDICAL                 4.089450
PERSONALIZATION         3.892743
PRODUCTIVITY            3.872036
LIFESTYLE               3.820271
FINANCE                 3.571798
SPORTS                  3.364738
COMMUNICATION           3.261207
HEALTH_AND_FITNESS      2.981675
PHOTOGRAPHY             2.909204
NEWS_AND_MAGAZINES      2.629672
SOCIAL                  2.474376
BOOKS_AND_REFERENCE     2.298375
TRAVEL_AND_LOCAL        2.267315
SHOPPING                2.091314
DATING                  1.770370
VIDEO_PLAYERS           1.687545
MAPS_AND_NAVIGATION     1.356248
EDUCATION               1.232012
FOOD_AND_DRINK          1.159540
ENTERTAINMENT           1.056010
AUTO_AND_VEHICLES       0.880008
LIBRARIES_AND_DEMO      0.869655
WEATHER                 0.817890
HOUSE_AND_HOME          0.766125
ART_AND_DESIGN          0.662594
EVENTS                  0.662594
PARENTING               0.621182
COMICS                  0.579770
BEAUTY                  0.548711
Name: proportion, dtype: float64
-------------------------
Type
Free    92.172292
Paid     7.827708
Name: proportion, dtype: float64
-------------------------
Content Rating
Everyone           81.820064
Teen               10.725748
Mature 17+          4.068744
Everyone 10+        3.333678
Adults only 18+     0.031059
Unrated             0.020706
Name: proportion, dtype: float64
-------------------------
Genres
Tools                       8.551610
Entertainment               5.808055
Education                   5.280050
Business                    4.348276
Medical                     4.089450
                              ...
Role Playing;Brain Games    0.010353
Strategy;Education          0.010353
Racing;Pretend Play         0.010353
Communication;Creativity    0.010353
Strategy;Creativity         0.010353
Name: proportion, Length: 118, dtype: float64
-------------------------
Current Ver
Varies with device    10.931510
1.0                    8.278935
1.1                    2.694021
1.2                    1.823645
2.0                    1.543881
                        ...
6.04                   0.010362
1.5.447                0.010362
1.0.612928             0.010362
0.3.4                  0.010362
2.0.148.0              0.010362
Name: proportion, Length: 2817, dtype: float64
-------------------------
Android Ver
4.1 and up            22.802112
4.0.3 and up          14.445480
4.0 and up            13.306410
Varies with device    10.251631
4.4 and up             8.470540
2.3 and up             6.378793
5.0 and up             5.301854
4.2 and up             3.852128
2.3.3 and up           2.826965
2.2 and up             2.474889
3.0 and up             2.392047
4.3 and up             2.288495
2.1 and up             1.377239
1.6 and up             1.201201
6.0 and up             0.559180
7.0 and up             0.434918
3.2 and up             0.372787
2.0 and up             0.331366
5.1 and up             0.227814
1.5 and up             0.207104
4.4W and up            0.113907
3.1 and up             0.103552
2.0.1 and up           0.072486
8.0 and up             0.062131
7.1 and up             0.031066
4.0.3 - 7.1.1          0.020710
5.0 - 8.0              0.020710
1.0 and up             0.020710
7.0 - 7.1.1            0.010355
4.1 - 7.1.1            0.010355
5.0 - 6.0              0.010355
2.2 - 7.1.1            0.010355
5.0 - 7.1.1            0.010355
Name: proportion, dtype: float64
-------------------------

In [94]:
for col in categorical_features:
    print(df_copy[col].value_counts(normalize=True)*100)
    print('-------------------------')

App
Photo Editor & Candy Camera & Grid & ScrapBook        0.010353
Coloring book moana                                   0.010353
U Launcher Lite – FREE Live Cool Themes, Hide Apps    0.010353
Sketch - Draw & Paint                                 0.010353
Pixel Draw - Number Art Coloring Book                 0.010353
                                                        ...
Sya9a Maroc - FR                                      0.010353
Fr. Mike Schmitz Audio Teachings                      0.010353
Parkinson Exercices FR                                0.010353
The SCP Foundation DB fr nn5n                         0.010353
iHoroscope - 2018 Daily Horoscope & Astrology         0.010353
Name: proportion, Length: 9659, dtype: float64
-------------------------
Category
FAMILY                 18.966767
GAME                    9.928564
TOOLS                   8.561963
BUSINESS                4.348276
MEDICAL                 4.089450
PERSONALIZATION         3.892743
PRODUCTIVITY            3.872036
LIFESTYLE               3.820271
FINANCE                 3.571798
SPORTS                  3.364738
COMMUNICATION           3.261207
HEALTH_AND_FITNESS      2.981675
PHOTOGRAPHY             2.909204
NEWS_AND_MAGAZINES      2.629672
SOCIAL                  2.474376
BOOKS_AND_REFERENCE     2.298375
TRAVEL_AND_LOCAL        2.267315
SHOPPING                2.091314
DATING                  1.770370
VIDEO_PLAYERS           1.687545
MAPS_AND_NAVIGATION     1.356248
EDUCATION               1.232012
FOOD_AND_DRINK          1.159540
ENTERTAINMENT           1.056010
AUTO_AND_VEHICLES       0.880008
LIBRARIES_AND_DEMO      0.869655
WEATHER                 0.817890
HOUSE_AND_HOME          0.766125
ART_AND_DESIGN          0.662594
EVENTS                  0.662594
PARENTING               0.621182
COMICS                  0.579770
BEAUTY                  0.548711
Name: proportion, dtype: float64
-------------------------
Type
Free    92.172292
Paid     7.827708
Name: proportion, dtype: float64
-------------------------
Content Rating
Everyone           81.820064
Teen               10.725748
Mature 17+          4.068744
Everyone 10+        3.333678
Adults only 18+     0.031059
Unrated             0.020706
Name: proportion, dtype: float64
-------------------------
Genres
Tools                       8.551610
Entertainment               5.808055
Education                   5.280050
Business                    4.348276
Medical                     4.089450
                              ...
Role Playing;Brain Games    0.010353
Strategy;Education          0.010353
Racing;Pretend Play         0.010353
Communication;Creativity    0.010353
Strategy;Creativity         0.010353
Name: proportion, Length: 118, dtype: float64
-------------------------
Current Ver
Varies with device    10.931510
1.0                    8.278935
1.1                    2.694021
1.2                    1.823645
2.0                    1.543881
                        ...
6.04                   0.010362
1.5.447                0.010362
1.0.612928             0.010362
0.3.4                  0.010362
2.0.148.0              0.010362
Name: proportion, Length: 2817, dtype: float64
-------------------------
Android Ver
4.1 and up            22.802112
4.0.3 and up          14.445480
4.0 and up            13.306410
Varies with device    10.251631
4.4 and up             8.470540
2.3 and up             6.378793
5.0 and up             5.301854
4.2 and up             3.852128
2.3.3 and up           2.826965
2.2 and up             2.474889
3.0 and up             2.392047
4.3 and up             2.288495
2.1 and up             1.377239
1.6 and up             1.201201
6.0 and up             0.559180
7.0 and up             0.434918
3.2 and up             0.372787
2.0 and up             0.331366
5.1 and up             0.227814
1.5 and up             0.207104
4.4W and up            0.113907
3.1 and up             0.103552
2.0.1 and up           0.072486
8.0 and up             0.062131
7.1 and up             0.031066
4.0.3 - 7.1.1          0.020710
5.0 - 8.0              0.020710
1.0 and up             0.020710
7.0 - 7.1.1            0.010355
4.1 - 7.1.1            0.010355
5.0 - 6.0              0.010355
2.2 - 7.1.1            0.010355
5.0 - 7.1.1            0.010355
Name: proportion, dtype: float64
-------------------------